// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VIcigAgaTgavx9cMPQvtui1XWWL9tro',
    appId: '1:763486021642:web:c640e53558029588ce17f3',
    messagingSenderId: '763486021642',
    projectId: 'chirk-e14c5',
    authDomain: 'chirk-e14c5.firebaseapp.com',
    storageBucket: 'chirk-e14c5.appspot.com',
    measurementId: 'G-YBM9F646LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIwuJGdgcwBF1_Nqt8fhS9IHkt-4ZMXk',
    appId: '1:763486021642:android:0a137f2a375f40d8ce17f3',
    messagingSenderId: '763486021642',
    projectId: 'chirk-e14c5',
    storageBucket: 'chirk-e14c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH54KoTx372KWU3lDa9kVv9eiQx2-QdqI',
    appId: '1:763486021642:ios:4c2845cd92860af9ce17f3',
    messagingSenderId: '763486021642',
    projectId: 'chirk-e14c5',
    storageBucket: 'chirk-e14c5.appspot.com',
    iosClientId: '763486021642-sa7l3ltoqvp8ojbobj8514h1v65k9aa0.apps.googleusercontent.com',
    iosBundleId: 'ru.vsu.cs.tp.chirk',
  );
}
